TabloidMVC/Models/Post.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TabloidMVC.Models
{
    public class Post
    {
        public int Id { get; set; }
        public int CurrentUserId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [DisplayName("Header Image URL")]
        public string ImageLocation { get; set; }

        public DateTime CreateDateTime { get; set; }

        [DisplayName("Published")]
        [DataType(DataType.Date)]
        public DateTime? PublishDateTime { get; set; }

        public bool IsApproved { get; set; }

        [Required]
        [DisplayName("Category")]
        public int? CategoryId { get; set; }
        public Category Category { get; set; }

        [DisplayName("Author")]
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
    }
}

TabloidMVC/Controllers/MyPostsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    public class MyPostsController : Controller
    {
        public IPostRepository _postRepository;
        public MyPostsController(IPostRepository postRepository)
        {
            _postRepository = postRepository;
        } 
        // GET: MyPostsController
        public ActionResult Index()
        {
            int userId = GetCurrentUserProfileId();

            var userPosts = _postRepository.GetUsersPublishedPostsByUserId(userId);

            return View(userPosts);
        }

        // GET: MyPostsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MyPostsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MyPostsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MyPostsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MyPostsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MyPostsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MyPostsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

TabloidMVC/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualBasic;
using System.Security.Claims;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;
using TabloidMVC.Models;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace TabloidMVC.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IUserProfileRepository _userRepository;

        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository, IUserProfileRepository userRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
            _userRepository = userRepository;
        }

        
        public IActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                var vm = new PostDropDownViewModel()
                {
                    Posts = _postRepository.ADMINGetAllPublishedPosts(),
                    UserIds = _userRepository.GetAll(),
                    CategoriesIds = _categoryRepository.GetAll()
                };

                vm.selectedCategory = 0;
                vm.selectedUser = 0;
                vm.UserIds.Add(new UserProfile()
                {
                    Id = 0,
                    FirstName = "-select-"
                });
                vm.CategoriesIds.Add(new Category()
                {
                    Id = 0,
                    Name = "-select-"
                });
                return View(vm);
            } else
            {
                var vm = new PostDropDownViewModel()
                {
                    Posts = _postRepository.GetAllPublishedPosts(),
                    UserIds = _userRepository.GetAll(),
                    CategoriesIds = _categoryRepository.GetAll()
                };

                vm.selectedCategory = 0;
                vm.selectedUser = 0;
                vm.UserIds.Add(new UserProfile()
                {
                    Id = 0,
                    FirstName = "-select-"
                });
                vm.CategoriesIds.Add(new Category()
                {
                    Id = 0,
                    Name = "-select-"
                });
                return View(vm);
            }
        }

        [HttpPost]
        public IActionResult Index(PostDropDownViewModel vm)
        {
            var Posts = new List<Post>();

            if(vm.selectedCategory != 0 && vm.selectedUser != 0)
            {
                Posts = _postRepository.GetUsersPublishedPostsByCategoryIdAndUserId(vm.selectedUser, vm.selectedCategory);
            }
            else if(vm.selectedUser != 0)
            {
                Posts = _postRepository.GetUsersPublishedPostsByUserId(vm.selectedUser);
            }
            else if(vm.selectedCategory != 0)
            {
                Posts = _postRepository.GetUsersPublishedPostsByCategoryId(vm.selectedCategory);
            }
            else
            {
                Posts = _postRepository.GetAllPublishedPosts();
            }

            var UserIds = _userRepository.GetAll();
            var CategoriesIds = _categoryRepository.GetAll();
            UserIds.Add(new UserProfile()
            {
                Id = 0,
                FirstName = "-select-"
            });
            CategoriesIds.Add(new Category()
            {
                Id = 0,
                Name = "-select-"
            });
            vm = new PostDropDownViewModel()
            {
                Posts = Posts,
                UserIds = UserIds,
                CategoriesIds = CategoriesIds,
            };
            return View(vm);
        }

        public IActionResult Details(int id)
        {
            var post = _postRepository.GetPublishedPostById(id);
            if (post == null)
            {
                int userId = GetCurrentUserProfileId();
                post = _postRepository.GetUserPostById(id, userId);
                if (post == null)
                {
                    return NotFound();
                }
            }

            post.CurrentUserId = GetCurrentUserProfileId();

            return View(post);
        }

        public IActionResult Subscribe(int id)
        {

            try
            {

                var currentUserId = GetCurrentUserProfileId();
                var userId = _postRepository.GetAuthorIdByPostId(id);
                var currentDateTime = DateTime.Now;

                _postRepository.Subscribe(userId, currentUserId, currentDateTime);

                return RedirectToAction("Details", "Post", new { id = id });
            }
            catch(Exception ex)
            {
                return View();
            };

        }

        public IActionResult Create()
        {
            var vm = new PostCreateViewModel();
            vm.CategoryOptions = _categoryRepository.GetAll();
            return View(vm);
        }

        public IActionResult Edit(int id)
        {
            Post post = _postRepository.GetPublishedPostById(id);
            Console.WriteLine($"Post Id: {id}");
            return View(post);
        }

        [HttpPost]
        public IActionResult Edit(Post post)
        {
            try
            {
                _postRepository.UpdatePost(post);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
                return View(post);
            }

            
        }

        [HttpPost]
        public IActionResult Create(PostCreateViewModel vm)
        {
            try
            {
                vm.Post.CreateDateTime = DateAndTime.Now;
                vm.Post.IsApproved = true;
                vm.Post.UserProfileId = GetCurrentUserProfileId();

                _postRepository.Add(vm.Post);

                return RedirectToAction("Details", new { id = vm.Post.Id });
            } 
            catch
            {
                vm.CategoryOptions = _categoryRepository.GetAll();
                return View(vm);
            }
        }

        public IActionResult Delete(int id)
        {
            _postRepository.Remove(id);
            return RedirectToAction("Index");
        }

        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

TabloidMVC/Controllers/ReactionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TabloidMVC.Models;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    public class ReactionController : Controller
    {
        private readonly IReactionRepository _reactionRepository;
        public ReactionController(IReactionRepository reactionRepository)
        {
            _reactionRepository = reactionRepository;
        }
        // GET: ReactionController
        public ActionResult Index()
        {
            List<Reaction> reactions = _reactionRepository.GetAll();
            return View(reactions);
        }


        // GET: ReactionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ReactionController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReactionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Reaction reaction)
        {
            try
            {
                _reactionRepository.AddReaction(reaction);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(reaction);
            }
        }

        // GET: ReactionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ReactionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReactionController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ReactionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TabloidMVC/Views/Post/Create.cshtml
@model TabloidMVC.Models.ViewModels.PostCreateViewModel

@{
    ViewData["Title"] = "Create";
}



<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="card col-md-12 col-lg-8">
            <h3 class="mt-3 text-primary text-center card-title">What do you have to say?</h3>
            <form class="mt-5 card-body" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Post.Title" class="control-label"></label>
                    <input asp-for="Post.Title" class="form-control" />
                    <span asp-validation-for="Post.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.ImageLocation" class="control-label"></label>
                    <input asp-for="Post.ImageLocation" class="form-control" />
                    <span asp-validation-for="Post.ImageLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.PublishDateTime" class="control-label"></label>
                    <input asp-for="Post.PublishDateTime" class="form-control" />
                    <span asp-validation-for="Post.PublishDateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.CategoryId" class="control-label"></label>
                    <select asp-for="Post.CategoryId" class="form-control">
                        @foreach (var category in Model.CategoryOptions)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Post.CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.Content" class="control-label"></label>
                    <textarea asp-for="Post.Content" rows="15" class="form-control post__content-input"></textarea>
                    <span asp-validation-for="Post.Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="SAVE" class="btn btn-primary btn-block" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Post/Delete.cshtml
@model TabloidMVC.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsApproved)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserProfileId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserProfileId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TabloidMVC/Views/Post/Details.cshtml
@model TabloidMVC.Models.Post

@{
    ViewData["Title"] = $"Post - {Model.Title}";
}

<div class="container pt-5">
    <div class="post">
        <section class="px-3">
            <div class="row justify-content-between">
                <h1 class="text-secondary">@Model.Title</h1>
                <h1 class="text-black-50">@Model.Category.Name</h1>
            </div>
            <div class="row justify-content-between">
                <p class="text-secondary">Written by @Model.UserProfile.DisplayName</p>
                <p class="text-black-50">Published on @Html.DisplayFor(model => model.PublishDateTime)</p>
            </div>
            <div class="row">
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Edit">
                    <i class="fas fa-pencil-alt"></i>
                </a>
                <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Delete">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
        </section>
        <hr />
        @if (!string.IsNullOrWhiteSpace(Model.ImageLocation))
        {
            <section class="row justify-content-center">
                <div>
                    <img src="@Model.ImageLocation" />
                </div>
            </section>
        }
        <section class="row post__content">
            <p class="col-sm-12 mt-5">@Html.DisplayFor(model => model.Content)</p>
        </section>
        <div class="row justify-content-between">
            <a asp-controller="Comment" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Comment">Add Comment</a>
            <a asp-controller="Comment" asp-action="CommentList" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Comment">View Comments</a>

            <a asp-controller="Reaction" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Comment">Add Reaction</a>
          
            @if (Model.UserProfileId != Model.CurrentUserId)
            {
                <a asp-action="Subscribe" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Subscribe">Subscribe</a>
            }



        </div>
       
    </div>
</div>

TabloidMVC/Views/Post/Edit.cshtml
@model TabloidMVC.Models.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageLocation" class="control-label"></label>
                <input asp-for="ImageLocation" class="form-control" />
                <span asp-validation-for="ImageLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDateTime" class="control-label"></label>
                <input asp-for="CreateDateTime" class="form-control" />
                <span asp-validation-for="CreateDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishDateTime" class="control-label"></label>
                <input asp-for="PublishDateTime" class="form-control" />
                <span asp-validation-for="PublishDateTime" class="text-danger"></span>
            </div>
            @if (User.IsInRole("Admin"))
            {
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsApproved" /> @Html.DisplayNameFor(model => model.IsApproved)
                    </label>
                </div>
            }
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserProfileId" class="control-label"></label>
                <input asp-for="UserProfileId" class="form-control" />
                <span asp-validation-for="UserProfileId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Post/Index.cshtml
@model TabloidMVC.Models.ViewModels.PostDropDownViewModel

@{
    ViewData["Title"] = "Index";
}


<div class="container pt-5">
    <h1>Posts</h1>

    <p>
        <a class="btn btn-primary" asp-action="Create">New Post</a>

        @using (Html.BeginForm())
        {
            <ul>

                <li>
                    <h4>Author</h4>
                    @Html.DropDownListFor(m => m.selectedUser, new SelectList(Model.UserIds, "Id", "FullName"))
                </li>

                <li>
                    <h4>Category</h4>
                    @Html.DropDownListFor(m => m.selectedCategory, new SelectList(Model.CategoriesIds, "Id", "Name"))
                </li>

            </ul>
            <input class="btn btn-primary" type="submit" value="Filter" />
        }
        
        <br />
        <a class="btn btn-primary" asp-action="Index">Reset Filters</a>
    </p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Post.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post.UserProfileId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post.CategoryId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Post.PublishDateTime)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Posts)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfile.DisplayName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublishDateTime)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="View">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Edit">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TabloidMVC/Views/Post/MyPosts.cshtml
@model IEnumerable<TabloidMVC.Models.Post>

@{
    ViewData["Title"] = "MyPosts";
}

<div class="container pt-5">
    <h1>My Posts</h1>

    <p>
        <a class="btn btn-primary" asp-action="Create">New Post</a>
    </p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserProfileId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublishDateTime)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfile.DisplayName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublishDateTime)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="View">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Edit">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>